'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Entity
Imports System.Data.Entity.Infrastructure

Partial Public Class FPC_DBEntities
    Inherits DbContext

    Public Sub New()
        MyBase.New("name=FPC_DBEntities")
    End Sub

    Protected Overrides Sub OnModelCreating(modelBuilder As DbModelBuilder)
        Throw New UnintentionalCodeFirstException()
    End Sub

    Public Overridable Property FPC_Departments() As DbSet(Of FPC_Departments)
    Public Overridable Property FPC_Employees() As DbSet(Of FPC_Employees)

End Class
