'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class FPC_Departments
    Public Property ID As Integer
    Public Property DepartmentName As String
    Public Property Remarks As String
    Public Property BasicDep As Integer
    Public Property ViewOrder As Nullable(Of Integer)
    Public Property CreateID As Nullable(Of Integer)
    Public Property Valid As Boolean

End Class
