'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class FPC_Employees
    Public Property ID As Integer
    Public Property WorkNo As Integer
    Public Property Name As String
    Public Property [Alias] As String
    Public Property PWD As String
    Public Property PWD_ask As Nullable(Of Boolean)
    Public Property DepID As Integer
    Public Property JobStatus As Integer
    Public Property SalaryStatus As Integer
    Public Property Rights As Integer
    Public Property WorkTime As Date
    Public Property TodayBalanceTime As Nullable(Of Date)
    Public Property TotalBalanceTime As Nullable(Of Date)
    Public Property BalanceClearDate As Nullable(Of Date)
    Public Property HomePhone As String
    Public Property LocalPhoneNo As String
    Public Property HomeMobile As String
    Public Property Mobile As String
    Public Property EMail As String
    Public Property HomeEmail As String
    Public Property Remarks As String
    Public Property Valid As Boolean

    Public Overridable Property FPC_Employees1 As FPC_Employees
    Public Overridable Property FPC_Employees2 As FPC_Employees

End Class
